export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const AUTENTICACION_EXITO = 'AUTENTICACION_EXITO';
export const AUTENTICACION_ERROR = 'AUTENTICACION_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';
