// REGISTRO DE USUARIOS
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

// AUTENTICACION DEL USUARIO
export const AUTENTICACION_EXITO = 'AUTENTICACION_EXITO';
export const AUTENTICACION_ERROR = 'AUTENTICACION_ERROR';

// OPERACIONES CON EL USUARIO AUTENTICADO
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';

// ALERTAS
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

// SUBIDA DE ARCHIVOS
export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

// CREACION DE LOS ENLACES
export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

// REINICIAR STATE
export const LIMPIAR_STATE = 'LIMPIAR_STATE';
